version: '2.0'
services:
  terror_recog:
    image: registry.tongdun.me/xdsec/ai.terror.gen:v1-0-6-2020902
    restart: always
    ports:
        - 4000:8088
    volumes:
        - /etc/localtime:/etc/localtime:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
      - worker=1
  logo_rec:
      image: registry.tongdun.me/xdsec/ai-logo-gen:1.7.2
      restart: always
      ports:
          - 4001:8088
      environment:
          - WORKER_NUM=1
          - NVIDIA_VISIBLE_DEVICES=2
  terrror_det:
      image: registry.tongdun.me/xdsec/terror-det-retinanet:0.1
      restart: always
      ports:
          - 4002:8088
      environment:
          - WORKER_NUM=1
          - NVIDIA_VISIBLE_DEVICES=2
