version: '2.4'
services:
    logo_rec:
        image: registry.tongdun.me/xdsec/ai-logo-gen:1.7.2
        restart: always
        ports:
            - 8093:8088
        environment:
            - WORKER_NUM=1
            - NVIDIA_VISIBLE_DEVICES=0
